spring:
  application:
    name: leon-cloud-nacos-client
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: c6cdd823-110c-4fec-b155-27cc25e5348a
server:
  port: 8862