server:
  port: 8699
spring:
  application:
    name: leon-gateways-gateway
  profiles:
    active: weight_route # 当前激活的配置文件
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  cloud:
    gateway:
      routes:
        - id: after_route # 我们自定义的路由 ID，保持唯一
          uri: lb://leon-cloud-ribbon-server # 目标服务地址
          predicates: # 路由条件，支持多个参数
            - After=2021-08-02T18:30:11.965+08:00[Asia/Shanghai] # 请求时间在这个指定时间之后才能访问
  profiles: after_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: before_route
          uri: lb://leon-cloud-ribbon-server
          predicates:
            - Before=2091-01-08T18:30:11.965+08:00[Asia/Shanghai]
  profiles: before_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: between_route
          uri: lb://leon-cloud-ribbon-server
          predicates:
            - Between=2020-01-08T18:30:11.965+08:00[Asia/Shanghai],2091-01-08T18:30:11.965+08:00[Asia/Shanghai]
  profiles: between_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: cookie_route
          uri: lb://leon-cloud-ribbon-server
          predicates:
            - Cookie=leoncloud, hello
  profiles: cookie_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: header_route
          uri: lb://leon-cloud-ribbon-server
          predicates:
            - Header=leoncloud, hello
  profiles: header_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: host_route
          uri: lb://leon-cloud-ribbon-server
          predicates:
            - Host=**.leoncloud.top
  profiles: host_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: lb://leon-cloud-ribbon-server
          predicates:
            #            - Method=GET,POST
            - Method=GET # 只允许 Get 请求
  profiles: method_route
---
---
spring:
  cloud:
    gateway:
      routes:
        - id: host_path_route
          uri: lb://leon-cloud-ribbon-server
          predicates:
            - Path=/user/{segment},/blue/{segment} # 匹配请求路径 RequestMapping 内容
  profiles: host_path_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: query_route
          uri: lb://leon-cloud-ribbon-server
          predicates:
            - Query=green
  profiles: query_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: weight_heigh
          uri: lb://leon-cloud-ribbon-server
          predicates:
            - Weight=group1, 8
        - id: weight_low
          uri: lb://leon-cloud-ribbon-server-bak #修改配置，换一个服务名启动
          predicates:
            - Weight=group1, 2
  profiles: weight_route
---
spring:
  cloud:
    gateway:
      routes:
        - id: map_request_header_route
          uri: lb://leon-cloud-ribbon-server
          predicates:
            - After=2020-01-08T18:30:11.965+08:00[Asia/Shanghai]
          filters:
            - MapRequestHeader=Blue, X-Request-Red
  profiles: map_request_header_route