server:
  port: 8763
spring:
  application:
    name: leon-register-eureka-client
eureka:
  client:
    service-url:
      # 集群用逗号隔开
#      defaultZone: http://leoncloud:123456@localhost:8761/eureka,http://leoncloud:123456@localhost:8762/eureka # 密码
      defaultZone: http://localhost:8761/eureka