server:
  port: 8771
spring:
  application:
    name: leon-cloud-feign-okhttp
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    com.leon.feign.client: debug
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true