server:
  port: 8772
spring:
  application:
#    name: leon-cloud-ribbon-client
#    name: leon-feign
    name: leon-cloud-ribbon-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka