server:
  port: 8863
spring:
  application:
    name: leon-cloud-actuator
eureka:
  client:
    service-url:
#      defaultZone: http://leoncloud:123456@localhost:8761/eureka # 密码登录
      defaultZone: http://localhost:8761/eureka